apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  opt1:
    env:
      deploy: "true"
    steps:
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        if: ${{ env.deploy == 'true'}}
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        if: ${{ env.deploy == 'true'}}
        uses: cloudbees-io/checkout@v1
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        name: Create credential file from secret
        run: |
          rm -rf ${HOME}/.kube
          mkdir ${HOME}/.kube && cat >> ${HOME}/.kube/config.json << EOF
          ${{ secrets.mlcbMultilinePass }}
          EOF
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        if: ${{ env.deploy == 'true'}}
        name: Google Cloud authentication and HELM creation, install and port fwd
        run: |
          gcloud auth login --cred-file=${HOME}/.kube/config.json 
          gcloud config set project mlcbplatformproject
          gcloud container clusters get-credentials mlcb-platform-cluster-ap002 --region us-east1 --project mlcbplatformproject 
          helm install what-the-helm what-the-helm/ --wait          
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        if: ${{ env.deploy != 'true'}}
        name: Google Cloud authentication and HELM uninstall
        run: |
          gcloud auth login --cred-file=${HOME}/.kube/config.json 
          gcloud config set project mlcbplatformproject
          gcloud container clusters get-credentials mlcb-platform-cluster-ap002 --region us-east1 --project mlcbplatformproject 
          helm uninstall what-the-helm